[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dice_duel = "Djg4PX3upqax7GWrxWUjF3ydhbDDPqugM5QTsoNu14xx"

[programs.localnet]
dice_duel = "Djg4PX3upqax7GWrxWUjF3ydhbDDPqugM5QTsoNu14xx"

[programs.mainnet]
dice_duel = "Djg4PX3upqax7GWrxWUjF3ydhbDDPqugM5QTsoNu14xx"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/dice_duel.ts"
